
name: build-image

on:
  workflow_dispatch:
    outputs:
      IMAGE_TAG:
        description: "The tag of the image create"
        value: ${{ jobs.docker-build-image.outputs.IMAGE_TAG }}
    inputs:
      BUILD_APP_WD:
        required: true
        type: string
      ECR_REPOSITORY:
        required: true
        type: string
jobs:
  docker-build-image:
    runs-on: ubuntu-latest
    outputs:
      IMAGE_TAG: ${{ steps.build-image.outputs.IMAGE_TAG }}
    steps:
      - name: checkout dockerfile
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-region: eu-west-1

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build, tag, and push image to Amazon ECR
        id: build-image
        working-directory: ${{ inputs.BUILD_APP_WD }}
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: ${{ inputs.ECR_REPOSITORY }}
          IMAGE_TAG: ${{ inputs.IMAGE_TAG }}
        run: |
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
          echo "::set-output name=IMAGE_TAG::$IMAGE_TAG"